/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WillApp;

import java.sql.Connection;
import util.connectionFactory;

public class App {
  
    public static void main(String[] args) {
        Connection c = ConnectionFactory.getConnection();
        
        Connectionfactory.closeConnection(c);
    }
}
